version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - local-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
    - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - local-net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      retries: 10

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - local-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eureka-server:8761/" ]
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "10006:10006"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=native
    networks:
      - local-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:10006/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "10004:10004"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - local-net

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "10001:10001"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - local-net

  employee-service:
    build: ./employee-service
    container_name: employee-service
    ports:
      - "10003:10003"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - local-net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "10002:10002"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - local-net

networks:
  local-net:
    driver: bridge


