server:
  port: 10004

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:10001
          predicates:
            - Path=/users/**
        - id: employee-service
          uri: http://localhost:10003
          predicates:
            - Path=/employees/**
      default-filters:
        - AddResponseHeader=X-Gateway, SpringCloudGateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10005/eureka/
