spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:10006"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
