spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://config-server:10006"
eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
