server:
  port: 10004

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
      default-filters:
        - AddResponseHeader=X-Gateway, SpringCloudGateway