spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repository

server:
  port: 10006

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/