spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repository

server:
  port: 10006

management:
  endpoints:
    web:
      exposure:
        include: health

eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/